version: '3.8'
services:
  app:
    build: ./docker/php
    container_name: portfolio-system-php
    working_dir: /var/www
    volumes:
      - "./:/var/www"
    networks:
      - portfolio-system-network

  db:
    image: mysql:5.7
    container_name: portfolio-system-database
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    env_file:
      - ./.env
    networks:
      - portfolio-system-network

  nginx:
    image: nginx:alpine
    container_name: portfolio-system-nginx
    ports:
      - "8081:80"
    volumes:
      - "./:/var/www"
      - "./docker/nginx/conf.d/:/etc/nginx/conf.d/"
    networks:
      - portfolio-system-network

networks:
  portfolio-system-network:
    driver: bridge